external-libraries:
  - charms.tls_certificates_interface.v3.tls_certificates
  - charms.observability_libs.v1.kubernetes_service_patch
  - charms.loki_k8s.v1.loki_push_api
internal-libraries:
  - charms.ovn_central_k8s.v0.ovsdb
