external-libraries:
  - charms.observability_libs.v1.kubernetes_service_patch
  - charms.grafana_k8s.v0.grafana_dashboard
  - charms.loki_k8s.v1.loki_push_api
internal-libraries:
  - charms.keystone_k8s.v0.identity_resource
