external-libraries:
  - charms.rabbitmq_k8s.v0.rabbitmq
  - charms.certificate_transfer_interface.v0.certificate_transfer
  - charms.loki_k8s.v1.loki_push_api
internal-libraries:
  - charms.keystone_k8s.v0.identity_credentials
  - charms.gnocchi_k8s.v0.gnocchi_service
templates:
  - parts/identity-data-id-creds
  - parts/section-oslo-messaging-rabbit
  - parts/section-service-credentials-from-identity-service
  - ca-bundle.pem.j2
